// Does the 808 actually sound like a rap 808?
//
// "There are still no 808s" was the complaint two rounds running, and the
// second time it came with the specific thing that was missing: "the true
// distortion sound that you can find in rap songs". That is a measurable
// claim, so this measures it instead of guessing again.
//
// What a rap 808 is, physically:
//
//  * a sine fundamental, usually somewhere around C1-G1 (33-49Hz), which
//    carries the weight;
//  * a large amount of HARMONIC energy above it, generated by saturation or
//    clipping, which is the only part a phone speaker can reproduce at all -
//    the ear then infers the fundamental it cannot hear;
//  * a decay long enough to ring under the next bar.
//
// So three numbers per kit:
//
//   sub      share of energy below 80Hz          (the weight)
//   harm     share between 100Hz and 2kHz        (the audible part / the grit)
//   thd      harmonic energy / fundamental energy (how distorted it IS)
//
// A clean sine 808 scores thd near 0 no matter how loud it is. That was the
// whole problem: eight of the eleven kits were essentially clean, and a clean
// sine is inaudible on the speakers most people listen on.
//
// Run: node tools/measure-808.js [flavor ...]
const { chromium } = require("playwright");
const path = require("path");
const fs = require("fs");

const candidates = [
  "/opt/pw-browsers/chromium/chrome-linux/chrome",
  ...fs.existsSync("/opt/pw-browsers")
    ? fs.readdirSync("/opt/pw-browsers").filter((d) => d.startsWith("chromium-"))
        .map((d) => `/opt/pw-browsers/${d}/chrome-linux/chrome`)
    : [],
];
const ONLY = process.argv.slice(2);

(async () => {
  const browser = await chromium.launch({
    executablePath: candidates.find((p) => fs.existsSync(p)),
    args: ["--autoplay-policy=no-user-gesture-required", "--mute-audio"],
  });
  const page = await browser.newPage();
  const errors = [];
  page.on("pageerror", (e) => errors.push(String(e)));
  await page.goto("file://" + path.join(__dirname, "..", "index.html"));
  await page.waitForTimeout(400);

  const rows = await page.evaluate(async (ONLY_FLAVORS) => {
    const SR = 44100;
    const F0 = 41.2;          // E1, a very ordinary 808 root
    const DUR = 2.2;
    const pool = (typeof FLAVOR_POOLS !== "undefined" ? FLAVOR_POOLS.bass : []) || [];
    const list = ONLY_FLAVORS.length ? ONLY_FLAVORS : pool;
    const out = [];

    // Goertzel: one bin, exact frequency, no windowing surprises. Used rather
    // than a full FFT because the question is about specific harmonics of a
    // known fundamental, not about the whole spectrum.
    const bin = (d, f) => {
      const w = 2 * Math.PI * f / SR;
      const c = 2 * Math.cos(w);
      let s1 = 0, s2 = 0;
      for (let i = 0; i < d.length; i++) { const s = d[i] + c * s1 - s2; s2 = s1; s1 = s; }
      return Math.sqrt(s1 * s1 + s2 * s2 - c * s1 * s2) / d.length;
    };

    for (const flavor of list) {
      const ctx = new OfflineAudioContext(2, Math.ceil(SR * DUR), SR);
      const e = new BeatEngine();
      await e.ensureContext(ctx);
      // A real 808 pattern, not one hit: two notes so the glide between them
      // is part of what gets measured.
      e.playBass(0.02, F0, 0.9, 0.9, flavor);
      e.playBass(1.05, F0 * 1.5, 0.9, 0.9, flavor);
      const buf = await ctx.startRendering();
      const d = buf.getChannelData(0);

      let peak = 0, sum = 0;
      for (let i = 0; i < d.length; i++) { const a = Math.abs(d[i]); if (a > peak) peak = a; sum += d[i] * d[i]; }
      const rms = Math.sqrt(sum / d.length);
      if (rms < 1e-5) { out.push({ flavor, silent: true }); continue; }

      // Harmonics of the FIRST note only, so the pitch is known.
      const seg = d.subarray(Math.floor(SR * 0.03), Math.floor(SR * 0.95));
      const fund = bin(seg, F0);
      let harm = 0;
      for (let n = 2; n <= 24; n++) {
        const f = F0 * n;
        if (f > 4000) break;
        const m = bin(seg, f);
        harm += m * m;
      }
      harm = Math.sqrt(harm);

      // Coarse band energies over the whole render, by cascading a biquad
      // pair into a 4th-order Linkwitz-Riley split.
      //
      // Note the Q value. Web Audio's BiquadFilterNode takes Q for lowpass
      // and highpass in DECIBELS, not as the linear Q of the filter-design
      // textbooks - so the obvious `Q = Math.SQRT1_2` does not ask for a
      // Butterworth, it asks for a resonant peak. It was returning 1.97 for
      // the sub share of a signal, i.e. claiming a band held twice as much
      // energy as the whole signal it came from, which is how it got caught.
      // A linear Q of 0.7071 is 20*log10(0.7071) = -3.01dB.
      const LR4_Q = -3.0103;
      const band = async (type, hz) => {
        const c2 = new OfflineAudioContext(1, d.length, SR);
        const s = c2.createBufferSource();
        const mono = c2.createBuffer(1, d.length, SR);
        mono.copyToChannel(d, 0);
        s.buffer = mono;
        let node = s;
        for (let k = 0; k < 2; k++) {
          const f = c2.createBiquadFilter();
          f.type = type; f.frequency.value = hz; f.Q.value = LR4_Q;
          node.connect(f); node = f;
        }
        node.connect(c2.destination);
        s.start();
        const b = await c2.startRendering();
        const x = b.getChannelData(0);
        let t = 0;
        for (let i = 0; i < x.length; i++) t += x[i] * x[i];
        return t;
      };
      const total = sum || 1;
      const sub = await band("lowpass", 80);
      const above = await band("highpass", 100);

      out.push({
        flavor,
        rms: +rms.toFixed(4),
        crest: +(peak / rms).toFixed(2),
        sub: +(sub / total).toFixed(3),
        harm: +(above / total).toFixed(3),
        thd: +(fund > 1e-9 ? harm / fund : 0).toFixed(3),
      });
    }
    return out;
  }, ONLY);

  // One bar for every kit was the wrong expectation, and it flagged clean808 -
  // a kit whose entire job is to be the clean one - as a failure. These groups
  // mirror the K808_* groups in patterns.js, so a kit moved between groups is
  // automatically held to the new group's standard.
  const GROUPS = {
    clean:  { kits: ["clean808", "sub", "rumble808", "long808", "deep808"], min: 0, max: 0.55 },
    warm:   { kits: ["808", "true808", "glide808", "detuned808", "overdrive808",
                     "wide808", "slide808"], min: 0.45, max: 1.15 },
    hard:   { kits: ["hard808", "punch808", "knock808", "stab808", "bright808"], min: 0.5, max: 1.6 },
    filthy: { kits: ["dirty808", "distort808", "fuzz808", "grimy808", "rage808",
                     "memphis808"], min: 0.9, max: 3.0 },
  };
  const groupOf = (f) => Object.keys(GROUPS).find((g) => GROUPS[g].kits.includes(f));

  console.log("\nkit            rms    crest   sub<80  harm>100   THD    expectation");
  console.log("".padEnd(74, "-"));
  const failures = [];
  for (const r of rows) {
    if (r.silent) {
      console.log(`${r.flavor.padEnd(14)} SILENT`);
      failures.push(`${r.flavor} is silent`);
      continue;
    }
    const g = groupOf(r.flavor);
    let mark = "";
    if (g) {
      const { min, max } = GROUPS[g];
      if (r.thd < min) { mark = `  <-- ${g}, wanted THD >= ${min}`; failures.push(`${r.flavor}: THD ${r.thd} below ${g} floor ${min}`); }
      else if (r.thd > max) { mark = `  <-- ${g}, wanted THD <= ${max}`; failures.push(`${r.flavor}: THD ${r.thd} above ${g} ceiling ${max}`); }
      else mark = `  ${g} ok`;
    }
    console.log(`${r.flavor.padEnd(14)} ${String(r.rms).padEnd(6)} ${String(r.crest).padEnd(7)}` +
                ` ${String(r.sub).padEnd(7)} ${String(r.harm).padEnd(9)} ${String(r.thd).padEnd(6)}${mark}`);
  }

  const named = Object.values(GROUPS).reduce((a, g) => a + g.kits.length, 0);
  console.log(`\n${named} kits carry a written-down distortion expectation, ` +
              `${failures.length} outside it${failures.length ? ":\n  " + failures.join("\n  ") : ""}`);
  if (errors.length) console.log("page errors: " + errors.slice(0, 3).join(" | "));
  await browser.close();
  process.exit(failures.length ? 1 : 0);
})();
